graph = :digraph.new()
:digraph.add_vertex(graph, "s")
:digraph.add_vertex(graph, "a")
:digraph.add_vertex(graph, "b")
:digraph.add_vertex(graph, "m")
:digraph.add_vertex(graph, "n")
:digraph.add_vertex(graph, "x")
:digraph.add_vertex(graph, "y")
:digraph.add_vertex(graph, "e")
:digraph.add_edge(graph, "s", "a")
:digraph.add_edge(graph, "a", "b")
:digraph.add_edge(graph, "b", "e")
:digraph.add_edge(graph, "s", "m")
:digraph.add_edge(graph, "m", "n")
:digraph.add_edge(graph, "n", "e")
:digraph.add_edge(graph, "s", "x")
:digraph.add_edge(graph, "x", "y")
:digraph.add_edge(graph, "y", "e")

IO.inspect(:digraph_utils.reachable(["y"], graph))
# IO.inspect(:digraph.edges(graph))
